// flow-typed signature: 99e48c16017b61d141d441d8024f9c9f
// flow-typed version: <<STUB>>/tcomb-validation_v^3.4.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tcomb-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tcomb-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tcomb-validation/index' {
  declare module.exports: $Exports<'tcomb-validation'>;
}
declare module 'tcomb-validation/index.js' {
  declare module.exports: $Exports<'tcomb-validation'>;
}
